name: mon_app
description: Une application Flutter connectée développée par Oxy-One
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (multi-plateforme : Android, iOS, Web, macOS, Windows, Linux)
  firebase_core: ^4.1.0

  # Bluetooth (Android, iOS, Web, Windows, Linux, macOS)
  flutter_blue_plus: ^1.35.10

  # Permissions (Android, iOS, Windows, macOS, Linux, Web)
  permission_handler: ^12.0.1

  # Icônes Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
